export { default as TextBox } from './features/TextBox'
export { default as PicsBox } from './features/PicsBox'
export { default as NavBar } from './Navbar'
export { default as Footer } from './Footer'
export { default as Contact } from './Contact'
export { default as ScrollToTop } from './ScrollToTop'